[general]
live_config_reload = true
ipc_socket = false

[window]
opacity = 1

[colors]
draw_bold_text_with_bright_colors = true
primary.background = "#060200"

[cursor]
style = {shape = "Block", blinking = "On"}

[font]
size = 10

[mouse]
hide_when_typing = true
